### ISSUE TITLE
Problemas com o template ao não definir variáveis de ambiente.

### ISSUE THREAD

**Issue by lucasrochagit** [nutes-uepb/template-base-ts#1]
Quando não é definido uma variável de ambiente (**arquivo .env**), não é possível subir a aplicação, base embora o build seja realizado.

**Comment by douglasrafael** [comment]
Adjusted! The dotenv module is now loaded only in the development or test environment.
Entretanto, for the development and testing environment, create the .env file in the root directory of your project and add your environment variables to new lines in the format `NAME=VALUE`. For example:
 ```js
DB_HOST=localhost
DB_USER=root
DB_PASS=mypass
```
The fastest way is to create a copy of the `.env.example` file :)

**NOTE**: For the production environment it is highly recommended not to use .env. Manually enter the environment variables that are required for your application.
